neowave/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.index, name='index'),
	path('register', views.register, name='register'),
	path('login', views.login, name= 'login'),
	path('logout', views.logout, name= 'logout'),
	path('useraccounts', views.useraccounts, name= 'useraccounts'),
    path('change_branch/', views.change_branch, name='change_branch'),
	path('createaccount', views.createaccount, name='createaccount'),
	path('initiate_transaction', views.initiate_transaction, name='initiate_transaction'),
	path('transaction_success/<str:bank_reference_no>/', views.transaction_success, name='transaction_success'),
	path('get_beneficiary_name/', views.get_beneficiary_name, name='get_beneficiary_name'),
	path('transaction_history', views.transaction_history, name= 'transaction_history'),
	path('userdetails', views.userdetails, name= 'userdetails'),
	path('cheque_details', views.cheque_details, name='cheque_details'),
	path('stop_cheque/', views.stop_cheque, name='stop_cheque'),
	path('get_statement/', views.get_statement, name='get_statement'),
	path('transaction_statement/', views.transaction_statement, name='transaction_statement'),
]

onlinebankingsystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('neowave.urls')),
]

neowave/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.
class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	firstname = models.CharField(max_length=100, default='')
	lastname = models.CharField(max_length=100, default='')
	fathername = models.CharField(max_length=100)
	mothername = models.CharField(max_length=100)
	street = models.CharField(max_length=255)
	city = models.CharField(max_length=100)
	pincode = models.CharField(max_length=6)
	mobilenumber = models.CharField(max_length=10)
	# nominee_name = models.CharField(max_length=100)
	# relationship_with_nominee = models.CharField(max_length=100)
	def __str__(self):
		return self.user.username

class Branch(models.Model):
	branch_name = models.CharField(max_length=100)
	address = models.CharField(max_length=255)
	ifsc = models.CharField(max_length=11, unique=True)
	pincode = models.CharField(max_length=6)
	def __str__(self):
		return self.branch_name

class Account(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	account_number = models.CharField(max_length=12, unique=True)
	branch_name = models.ForeignKey(Branch, on_delete=models.SET_NULL, null=True)
	ifsc = models.CharField(max_length=11, default='')
	balance = models.DecimalField(max_digits=10, decimal_places=2, default=0)
	opened_date = models.DateField(default=datetime.now)
	is_active = models.BooleanField(default=True)
	account_holder_name = models.CharField(max_length=255, default='')

	def save(self, *args, **kwargs):
		if self.pk is None:
			if self.branch_name:
				# Get the last 6 digits of the branch IFSC
				branch_ifsc_suffix = self.branch_name.ifsc[-6:]
				# Filter accounts with the same branch IFSC suffix
				accounts_with_suffix = Account.objects.filter(account_number__startswith=branch_ifsc_suffix)
				# Get the last account with the same branch IFSC suffix
				last_account_with_suffix = accounts_with_suffix.order_by('-account_number').first()
				
				if last_account_with_suffix:
					# Extract the numeric part of the account number
					last_account_number = int(last_account_with_suffix.account_number[-6:])
					# Generate the new account number by incrementing the last one
					new_account_number = str(last_account_number + 1).zfill(6)
					self.account_number = f"{branch_ifsc_suffix}{new_account_number}"
				else:
					# If no account exists for this branch, start with '000001'
					self.account_number = f"{branch_ifsc_suffix}000001"
				self.ifsc = self.branch_name.ifsc

		profile = self.user.profile
		self.account_holder_name = f"{profile.firstname} {profile.lastname}"
		super().save(*args, **kwargs)

	def __str__(self):
		return self.account_number

class Transaction(models.Model):
	sender_account = models.ForeignKey(Account, related_name='sent_transactions', on_delete=models.CASCADE)
	receiver_account_number = models.CharField(max_length=12)
	receiver_ifsc = models.CharField(max_length=11)
	amount = models.DecimalField(max_digits=10, decimal_places=2)
	sender_name = models.CharField(max_length=255, default='')
	beneficiary_name = models.CharField(max_length=255, default='')
	bank_reference_no = models.CharField(max_length=10, unique=True, blank=True, null=True)
	sender_balance_after_transaction = models.DecimalField(max_digits=10, decimal_places=2, default=0)
	receiver_balance_after_transaction = models.DecimalField(max_digits=10, decimal_places=2, default=0)
	timestamp = models.DateTimeField(auto_now_add=True)

	def save(self, *args, **kwargs):
		if not self.bank_reference_no:
			last_transaction = Transaction.objects.filter(bank_reference_no__isnull=False).order_by('-bank_reference_no').first()
			if last_transaction:
				last_reference_no = int(last_transaction.bank_reference_no[1:])
				new_reference_no = last_reference_no + 1
				self.bank_reference_no = f'B{str(new_reference_no).zfill(8)}'
			else:
				self.bank_reference_no = 'B00000001'

		if self.sender_account.balance < self.amount:
			raise ValueError('Insufficient balance.')
		
		self.sender_account.balance -= self.amount
		self.sender_balance_after_transaction = self.sender_account.balance

		try:
			receiver_account = Account.objects.get(account_number=self.receiver_account_number, ifsc=self.receiver_ifsc)
		except Account.DoesNotExist:
			raise ValueError('Receiver account does not exist.')

		receiver_account.balance += self.amount
		self.receiver_balance_after_transaction = receiver_account.balance

		self.sender_account.save()
		receiver_account.save()

		super().save(*args, **kwargs)

	def __str__(self):
		return self.bank_reference_no

class Cheque(models.Model):
	CHEQUE_STATUS_CHOICES = [
		('pending', 'Pending'),
		('cleared', 'Cleared'),
		('stopped', 'Stopped'),
	]
	STOP_REASON_CHOICES = [
		('lost', 'Cheque Reported Lost'),
		('stopped', 'Payment Stopped by Drawer'),
	]
	user_account = models.ForeignKey(Account, on_delete=models.CASCADE)
	cheque_number = models.CharField(max_length=20, unique=True)
	amount = models.DecimalField(max_digits=10, decimal_places=2)
	recipient = models.CharField(max_length=100)
	status = models.CharField(max_length=10, choices=CHEQUE_STATUS_CHOICES, default='pending')
	stop_reason = models.CharField(max_length=10, choices=STOP_REASON_CHOICES, blank=True, null=True)
	created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='cheques_created')
	stopped_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='cheques_stopped')
	created_at = models.DateTimeField(auto_now_add=True)

	def stop_payment(self, user, stop_reason):
		if self.status == 'pending':
			self.status = 'stopped'
			self.stopped_by = user
			self.stop_reason = stop_reason
			self.save()
			
	@property
	def issuer(self):
		return self.user_account.account_holder_name

	def __str__(self):
		return self.cheque_number

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta content="width=device-width, initial-scale=1.0" name="viewport">

	{% block title %}
	{% endblock %}
	<meta content="" name="description">
	<meta content="" name="keywords">

	<link href="{% static 'assets/favicon.png' %}" rel="icon">

	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
	
	<link href="{% static 'css/style.css' %}" rel="stylesheet">
	<link href="{% static 'css/nav.css' %}" rel="stylesheet">
	{% block stylecontent %}
	{% endblock %}
</head>

<body>


	<header id="header">
		<div class="navcontainer">
			<h1 class="logo"><a href="/">NeoWave</a></h1>
			{% if user.is_authenticated %}
			<div class="dropdown">
				<img src="{% static 'assets/usericon.png' %}" alt="Profile" class="service-icon">
				<ul class="dropdown-menu">
					<li><a href="/userdetails">Update&nbsp;Profile</a></li>
					<li><a class="blue-button-white-text" href="/logout">Logout</a></li>
				</ul>
			</div>
			{% else %}
			<div class="sign">
				<a href="/login"
					class="signin white-button-blue-text">Sign&nbsp;in</a>
				<a href="/register"
					class="signup blue-button-white-text">Sign&nbsp;up</a>
			</div>
			{% endif %}
		</div>
	</header>
		{% block bodycontent %}

		{% endblock %}
</body>

</html>

templates/cheque.html
{% extends 'base.html' %}
{% load static %}
<head>
	{% block title %}
	<title>Cheques - NeoWave Bank</title>
	{% endblock %}

	{% block stylecontent %}
	<link href="{% static 'css/modal.css' %}" rel="stylesheet">
	<link href="{% static 'css/animation.css' %}" rel="stylesheet">
	<link href="{% static 'css/form.css' %}" rel="stylesheet">
	<link href="{% static 'css/table.css' %}" rel="stylesheet">
	<link href="{% static 'css/style1.css' %}" rel="stylesheet">

		<style>
			.input {
				margin-bottom: 1rem;
			}
		</style>
	{% endblock %}
</head>
<body>
	{% block bodycontent %}
	<section>
		<div class="container">
			<div class="content">
				<h1>Cheque Details</h1>
				<form id="account_form" method="GET" action="{% url 'cheque_details' %}" class="form">
					<p class="input">Select Account</p>
					<select name="account_select" id="account_select" onchange="selectAccount()">
						<option value="" {% if not selected_account %}selected{% endif %}>-</option>
						{% for account in accounts %}
							<option value="{{ account.account_number }}" {% if account == selected_account %}selected{% endif %}>{{ account.account_number }}</option>
						{% endfor %}
					</select>
				</form><br>
				
				<table id="cheque_table">
					{% if selected_account %}
						<thead>
							<tr>
								<th>Date & Time</th>
								<th>Cheque Number</th>
								<th>Amount</th>
								<th>Issuer</th>
								<th>Recipient</th>
								<th>Status</th>
							</tr>
						</thead>
					{% endif %}
					<tbody>
						{% for cheque in cheques reversed %}
						<tr {% if cheque.status == 'pending' %}class="clickable" onclick="openPopup('{{ cheque.cheque_number }}')" {% endif %}>
							<td>{{ cheque.created_at }}</td>
							<td>{{ cheque.cheque_number }}</td>
							<td>{{ cheque.amount }}</td>
							<td>{{ cheque.issuer }}</td>
							<td>{{ cheque.recipient }}</td>
							<td class="{% if cheque.status == 'cleared' %}cleared{% elif cheque.status == 'pending' %}pending{% elif cheque.status == 'stopped' %}stopped{% endif %}">
								{{ cheque.status|capfirst }}
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>

				<div id="statusChangeModal" class="modal">
					<form id="statusChangeForm" class="animation">
						<div><span class="close" onclick="closeModal()">&times;</span><br></div>
						{% csrf_token %}
						<input type="hidden" id="chequeNumber" name="cheque_number" value="">
							<h2>Change Cheque Status</h2><br>
							<label for="stopReason">Stop Reason:</label>
							<select id="stopReason" name="stop_reason">
								<option value="">Select Stop Reason</option>
								{% for choice in stop_reason_choices %}
									<option value="{{ choice.0 }}">{{ choice.1 }}</option>
								{% endfor %}
							</select><br><br>
							<button type="button" onclick="stopCheque()">Stop Cheque</button>
					</form>
				</div>
				
				

				<script>
					function selectAccount() {
						document.getElementById("account_form").submit();
					}


					function closeModal() {
						document.getElementById("statusChangeModal").style.display = "none";
					}

					function openPopup(chequeNumber) {
						document.getElementById("statusChangeModal").style.display = "block";
						document.getElementById("chequeNumber").value = chequeNumber;
					}

					function stopCheque() {
						var formElement = document.getElementById("statusChangeForm");
						var formData = new FormData(formElement);

						var stopReason = document.getElementById("stopReason").value.trim();
						if (stopReason === "") {
							alert("Please select a stop reason.");
							return;
						}

						fetch("{% url 'stop_cheque' %}", {
							method: 'POST',
							body: formData,
						})
						.then(response => {
							if (response.ok) {
								console.log("Cheque stopped successfully.");
								closeModal();
								location.reload();
							} else {
								throw new Error("Failed to stop cheque.");
							}
						})
						.catch(error => {
							console.error('Error stopping cheque:', error);
							alert('An error occurred while stopping the cheque.');
							closeModal();
						});
					}
				</script>
			</div>
		</div>
	</section>
	{% endblock%}
</body>

templates/createaccount.html
{% extends 'base.html' %}
{% load static %}
<head>
	{% block title %}
	<title>Create a New Account- NeoWave Bank</title>
	{% endblock %}
	{% block stylecontent %}
	<link href="{% static 'css/animation.css' %}" rel="stylesheet">
	<link href="{% static 'css/form.css' %}" rel="stylesheet">
	{% endblock %}
</head>
<body>
	{% block bodycontent %}
	<style>
				.h1er {
		text-align: center; 
		background-color: rgba(255, 255, 255, 0.15); 
		backdrop-filter: blur(10px); 
		color: black; 
		padding: 20px; 
		border-radius: 10px;
		margin: 0 auto;
		width: fit-content;
}
	</style>
	<section>
		<div class="container">
			<div class="content">
				<h1 class="h1er">Create New Account</h1>
				<form method="post" class="animation">
					{% csrf_token %}
					<label for="branch">Select Branch:</label>
					<select name="branch" id="branch">
						{% for branch in branches %}
							<option value="{{ branch.id }}">{{ branch.branch_name }} ({{ branch.ifsc }})</option>
						{% endfor %}
					</select>
					<br><br>
					<button type="submit">Create Account</button>
					<br><br>
					<a href="{% url 'useraccounts' %}" style="text-align: center;">Back to User Accounts</a>
				</form>
			</div>
		</div>
	</section>
	{% endblock%}
</body>
</body>

templates/get_statement.html
{% extends 'base.html' %}
{% load static %}
<head>
	{% block title %}
	<title>Get Account Statement- NeoWave Bank</title>
	{% endblock %}
	{% block stylecontent %}
	<link href="{% static 'css/animation.css' %}" rel="stylesheet">
	<link href="{% static 'css/lessWidthAnimation.css' %}" rel="stylesheet">
	<link href="{% static 'css/form.css' %}" rel="stylesheet">
	{% endblock %}
</head>
<body>
	{% block bodycontent %}
	<section>
		<div class="container">
			<div class="content">
				<form method="post" action="{% url 'transaction_statement' %}" class="animation">
					<h1 >Get Statement</h1>
					{% csrf_token %}
					<p class="input">Month</p>
					<select id="month" name="month">
						<option value="">All Months</option>
						<option value="1">January</option>
						<option value="2">February</option>
						<option value="3">March</option>
						<option value="4">April</option>
						<option value="5">May</option>
						<option value="6">June</option>
						<option value="7">July</option>
						<option value="8">August</option>
						<option value="9">September</option>
						<option value="10">October</option>
						<option value="11">November</option>
						<option value="12">December</option>
					</select>
					<p class="input">Year</p>
					<select id="year" name="year">
						<option value="">Select Year</option>
						<option value="2024">2024</option>
						<option value="2023">2023</option>
					</select><br><br>
					<button type="submit">Generate Statement</button>
				</form>
			</div>
		</div>
	</section>
	{% endblock%}
</body>

templates/index.html
{% extends 'base.html' %}
{% load static %}
<head>
	{% block title %}
	<title>NeoWave Bank-Personal Banking & Netbanking Services</title>
	{% endblock %}
	{% block stylecontent %}
	<link href="{% static 'css/index-home.css' %}" rel="stylesheet">
	<link href="{% static 'css/index-login.css' %}" rel="stylesheet">
	<link href="{% static 'css/form.css' %}" rel="stylesheet">
	<link href="{% static 'css/sub-footer.css' %}" rel="stylesheet">
	{% endblock %}
</head>
<body>
	{% block bodycontent %}
	{% if user.is_authenticated %}
	<div class="welcome-div">
		<h1>Welcome, {{ user.username }}</h1>
	</div>
	<section class="services">
			<br><h2 style="text-align: center;">Our Services</h2>
			<div class="service-background">
				<div class="service-grid">
					<a href="/initiate_transaction">
					<div class="service-item">
						<img class="icon" src="../static/assets/moneyicon.png" alt="">
						<h3>Money Transfer</h3>
					</div></a>

					<a href="/useraccounts">
					<div class="service-item">
						<img class="icon" src="../static/assets/bankicon.png" alt="">
							<h3>Accounts</h3>
					</div></a>

					<a href="/transaction_history">
					<div class="service-item history">
						<img class="icon" src="../static/assets/transaction.png" alt="">
						<h3>Transaction History</h3>
					</div></a>

					<a href="/cheque_details">
					<div class="service-item">
						<img class="icon" src="../static/assets/cheque.png" alt="">
						<h3>Cheques</h3>
					</div></a>

					<a href="/get_statement">
					<div class="service-item">
						<img class="icon" src="../static/assets/money_insights.png" alt="">
						<h3>Money Insights</h3>
					</div></a>

					<a href="https://rbi.org.in/Scripts/Complaints.aspx">
					<div class="service-item">
						<img class="icon" src="../static/assets/emergency.png" alt="">
						<h3>Emergency</h3>
					</div></a>

				</div>
			</div>
	</section>
	{% else %}

	<section class="open-account">
		<div class="container">
			<div class="content open-account-div">
				<h1>FOR ALL THINGS MONEY</h1>
				<p class="manage-money">
					Manage your money with <span style="color: #2487CE;">peace of mind</span></p>
				<a href="./register" class="open-account-button">Open&nbsp;Savings&nbsp;Account</a>
				<div class="open-account-image">
					<img src="{% static 'assets/homepage.png' %}" alt="front page">
				</div>
				<h1>GET A SAVINGS ACCOUNT<br>UNLIKE ANY OTHER</h1>
			</div>
		</div>
	</section>

	<section class="bank-flash">
		<div class="container">
			<div class="content">
				<div class="bank-flash-div">
					<div class="bank-flash-image">
						<img src="{% static 'assets/zero balance.png' %}" alt="zero balance">
					</div>
					<div class="bank-flash-text">
						<h3>BANK IN FLASH</h3>
						<b><h1>Banking at the Speed of Thought: Open an Account in a Flash!</h1></b>
						<p>Experience lightning-fast account setup in 60 seconds! Swiftly create your bank account online with ease. No paperwork, no waiting - start banking in a flash!</p>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section class="welcome-gift">
		<div class="container">
			<div class="content">
				<div class="welcome-gift-div">
					<div class="welcome-gift-text">
						<h3>EXCLUSIVE WELCOME GIFT</h3>
						<b><h1>Welcome to Our Bank: Get Rs. 1000 as a Gift!</h1></b>
						<p>Welcome to Our Bank! As a new user, we're thrilled to offer you an exclusive welcome gift of Rs. 1000 when you open an account with us. Take advantage of this special offer and kickstart your banking journey with us today!</p>
					</div>
					<div class="welcome-gift-image">
						<img src="{% static 'assets/cashback.png' %}" alt="front page">
					</div>
				</div>
			</div>
		</div>
	</section>

	<footer>
		<div class="container">
			<div class="sub-footer">
				<p>Pritam Shaw</p>
				<div class="footer-box-social">
					<ul>
						<li><a href="https://github.com/thepritamshaw" target="_blank"><img
									src="{% static 'assets/github-transparent.png' %}" alt="Github"></a>
							<div class="placeholder"></div>
						</li>
						<li><a href="https://www.linkedin.com/in/thepritamshaw/" target="_blank"><img
									src="{% static 'assets/linkedin-transparent.png' %}" alt="Linkedin"></a>
							<div class="placeholder"></div>
						</li>
						<li><a href="https://www.twitter.com/thepritamshaw/" target="_blank"><img
									src="{% static 'assets/twitter-transparent.png' %}" alt="Twitter"></a>
							<div class="placeholder"></div>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</footer>
	{% endif %}
	{% endblock%}
</body>
</html>

templates/initiate_transaction.html
{% extends 'base.html' %}
{% load static %}
<head>
	{% block title %}
	<title>Fund Transfer- NeoWave Bank</title>
	{% endblock %}
	{% block stylecontent %}
		<link href="{% static 'css/form.css' %}" rel="stylesheet">
	{% endblock %}
</head>
<body>
	{% block bodycontent %}
	<section>
		<div class="container">
			<div class="content">
				<form method="post" class="form">
				<h1 class="h1er">Fund Transfer</h1><br>

				{% for message in messages %}
				<h5>{{message}}</h5>
				{% endfor %}
					{% csrf_token %}
					<p class="input">Select Sender Account:</p>
					<select name="sender_account">
						{% for account in sender_accounts %}
							<option value="{{ account.id }}">{{ account.account_number }}</option>
						{% endfor %}
					</select>
					<p class="input">Beneficiary Account Number:</p>
					<input type="text" name="beneficiary_account_number" required>
					<p class="input">Beneficiary IFSC Code:</p>
					<input type="text" name="beneficiary_ifsc" required>
					<p class="input">Beneficiary Name:</p>
					<input type="text" id="beneficiary_name" readonly>
					<p class="input">Amount</p>
					<input type="number" name="amount" step="0.01" min="0.01" required>
					<p class="input">Password:</p>
					<input type="password" name="password" required>
					<br><br>
					<button type="submit">Initiate Transaction</button><br><br>
					<a href="{% url 'useraccounts' %}">Back to User Accounts</a>
				</form>
			</div>
		</div>
	</section>
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script>
	$(document).ready(function() {
		$('input[name="beneficiary_account_number"], input[name="beneficiary_ifsc"]').on('input', function() {
			var accountNumber = $('input[name="beneficiary_account_number"]').val();
			var ifsc = $('input[name="beneficiary_ifsc"]').val();
			
			// Make AJAX request to fetch beneficiary name
			$.ajax({
				url: '/get_beneficiary_name/',
				type: 'GET',
				data: {
					'account_number': accountNumber,
					'ifsc': ifsc
				},
				success: function(response) {
					$('#beneficiary_name').val(response.beneficiary_name);
				},
				error: function(xhr, status, error) {
					console.error(xhr.responseText);
				}
			});
		});
	});
	</script>
	{% endblock%}
</body>

templates/login.html
{% extends 'base.html' %}
{% load static %}
<head>
	{% block title %}
	<title>Log in to your Account- NeoWave Bank</title>
	{% endblock %}
	{% block stylecontent %}
	<link href="{% static 'css/animation.css' %}" rel="stylesheet">
	<link href="{% static 'css/lessWidthAnimation.css' %}" rel="stylesheet">
	<link href="{% static 'css/form.css' %}" rel="stylesheet">
	{% endblock %}
</head>
<body>
	{% block bodycontent %}
	<section class="container" >
		<div class="container">
			<div class="content">
				<form action="login" method="POST" class="animation">
				<h1>Login Now</h1>
				{% for message in messages %}
				<h3>{{message}}</h3>
				{% endfor %}
					{% csrf_token %}
					<p class="input">Username</p>
					<input type="text" name="username" placeholder="Enter username here"/>
					<p class="input">Password</p>
					<input type="password" name="password" placeholder="Enter password here" /><br>
					<input type="submit" class="button" />
					<br>
					<a href="/register">Create New Account</a>
				</form>
				
			</div>
		</div>
	</section>
	{% endblock%}
</body>

templates/register.html
{% extends 'base.html' %}
{% load static %}
<head>
	{% block title %}
	<title>Open your Digital Savings Account- NeoWave Bank</title>
	{% endblock %}
	{% block stylecontent %}
		<link href="{% static 'css/form.css' %}" rel="stylesheet">
	{% endblock %}

</head>
<body>
	{% block bodycontent %}
	<section>
		<div class="container">
			<div class="content">
				<form method="POST" action="register" class="form">
				<h1 >Open your Online Savings Account</h1>

				{% for message in messages %}
				<h5>{{message}}</h5>
				{% endfor %}

					{% csrf_token %}

					<p class="input">First Name</p>
					<input type="text" name="firstname" />
					<p class="input">Last Name</p>
					<input type="text" name="lastname" />
					<p class="input">Father's Name</p>
					<input type="text" name="fathername" />
					<p class="input">Mother's Name</p>
					<input type="text" name="mothername" />
					<p class="input">Address</p>
					<p class="input">Street</p>
					<input type="text" name="street" />
					<p class="input">City</p>
					<input type="text" name="city" />
					<p class="input">Pincode</p>
					<input name="pincode" type="text" inputmode="numeric" pattern="[0-9]{6}">
					<p class="input">Mobile Number</p>
					<input name="mobilenumber" type="text" inputmode="numeric" pattern="[0-9]{10}">
					<p class="input">Choose Branch</p>
					<select name="branch">
						{% for branch in branches %}
							<option value="{{ branch.pk }}">{{ branch.branch_name }} ({{ branch.pincode}})</option>
						{% endfor %}
					</select>
					
					<p class="input">Create Username</p>
					<input type="text" name="username" />
					<p class="input">Email</p>
					<input type="email" name="email" />
					<p class="input">Enter Password</p>
					<input type="password" name="password" />
					<p class="input">Retype your Password</p>
					<input type="password" name="password1" /><br><br>
					<input type="submit" class="button" />

				</form>
			</div>
		</div>
	</section>
	{% endblock%}
</body>

templates/userdetails.html
{% extends 'base.html' %}
{% load static %}
<head>
	{% block title %}
	<title>Edit your Profile- NeoWave Bank</title>
	{% endblock %}
	{% block stylecontent %}
		<link href="{% static 'css/form.css' %}" rel="stylesheet">
	{% endblock %}
</head>
<body>
	{% block bodycontent %}
	<section>
		<div class="container">
			<div class="content">
				<form id="user-details-form" method="post" class="form">
					<h1>User Details</h1><br>
					{% csrf_token %}
					<p class="input">First Name</p>
					<input type="text" id="id_firstname" name="firstname" value="{{ profile.firstname }}" required><br>
					<p class="input">Last Name</p>
					<input type="text" id="id_lastname" name="lastname" value="{{ profile.lastname }}" required><br>
					<p class="input">Father's Name</p>
					<input type="text" id="id_fathername" name="fathername" value="{{ profile.fathername }}" required><br>
					<p class="input">Mother's Name</p>
					<input type="text" id="id_mothername" name="mothername" value="{{ profile.mothername }}" required><br>
					<p class="input">Street</p>
					<input type="text" id="id_street" name="street" value="{{ profile.street }}" required><br>
					<p class="input">City</p>
					<input type="text" id="id_city" name="city" value="{{ profile.city }}" required><br>
					<p class="input">Pincode</p>
					<input type="text" id="id_pincode" name="pincode" value="{{ profile.pincode }}" required><br>
					<p class="input">Mobile Number</p>
					<input type="text" id="id_mobilenumber" name="mobilenumber" value="{{ profile.mobilenumber }}" required><br>

					<br>
					<button type="submit">Save</button>
				</form>
			</div>
		</div>
	</section>
	{% endblock%}
</body>